# Generated by Django 4.2.6 on 2023-11-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_sell_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell_by',
        ),
    ]
