# Generated by Django 4.2.6 on 2023-11-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_sell_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartMapping',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
